### ISSUE TITLE
Mac机器运行源码报错

### ISSUE THREAD

**Issue by tobeflyboy** [xialeistudio/mybatis-generator-gui#7]
您好，在Mac系统下，运行最新源码报错
Exception in thread "main" java.lang.NullPointerException
	at com.ddhigh.mybatis.window.LoginWindow.<init>(LoginWindow.java:27)
	at com.ddhigh.mybatis.window.LoginWindow.main(LoginWindow.java:92)

**Comment by xialeistudio** [comment]
mac没带回来，明天我看看

**Comment by xialeistudio** [comment]
Mac 10.12.6用idea打开运行截图
![wx20180106-110257](https://user-images.githubusercontent.com/5136506/34635901-2ecd1438-f2d1-11e7-9198-158b0201ab63.png)
![wx20180106-110229](https://user-images.githubusercontent.com/5136506/34635902-2f00704e-f2d1-11e7-8183-098df7347b48.png)
![wx20180106-110220](https://user-images.githubusercontent.com/5136506/34635903-2f3323fe-f2d1-11e7-8d3f-0620cc018845.png)
